apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vector-db
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: vector-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 6333
